language: r
cache: packages
latex: false
fortran: false
pandoc: false
r_check_args: '--run-donttest'

matrix:
  include:
    - dist: trusty
    - dist: xenial
    - dist: xenial
      addons:
        apt:
          update: true
          packages: libavdevice-dev
          sources:
            - sourceline: 'ppa:jonathonf/ffmpeg-4'
            - sourceline: 'ppa:jonathonf/ffmpeg-3'
    - os: osx
      brew_packages: ffmpeg
    - os: osx
      disable_homebrew: true
    - os: osx
      osx_image: xcode7.3
      disable_homebrew: true

addons:
  apt:
    update: true
    packages: libavdevice-dev
    sources:
      - sourceline: 'ppa:jonathonf/ffmpeg-3'

warnings_are_errors: true

notifications:
  email:
    on_success: change
    on_failure: change
