language: r
cache: packages
latex: false
fortran: false
pandoc: false

matrix:
  include:
    - os: linux
    - os: osx
      osx_image: xcode9.3
      brew_packages: ffmpeg

addons:
  apt:
    update: true
    sources:
      - sourceline: 'ppa:jonathonf/ffmpeg-4'
      - sourceline: 'ppa:jonathonf/ffmpeg-3'
    packages:
      - libavfilter-dev

warnings_are_errors: true

notifications:
  email:
    on_success: change
    on_failure: change
